/// https://www.w3.org/2021/06/musicxml40/musicxml-reference/data-types/accidental-value/
enum AccidentalValue {
  sharp,
  natural,
  flat,
  doubleSharp,
  sharpSharp,
  flatFlat,
  naturalSharp,
  naturalFlat,
  quarterFlat,
  quarterSharp,
  threeQuartersFlat,
  threeQuartersSharp,
  sharpDown,
  sharpUp,
  naturalDown,
  naturalUp,
  flatDown,
  flatUp,
  doubleSharpDown,
  doubleSharpUp,
  flatFlatDown,
  flatFlatUp,
  arrowDown,
  arrowUp,
  tripleSharp,
  tripleFlat,
  slashQuarterSharp,
  slashSharp,
  slashFlat,
  doubleSlashFlat,
  sharp1,
  sharp2,
  sharp3,
  sharp5,
  flat1,
  flat2,
  flat3,
  flat4,
  sori,
  koron,
  other,
}

const accidentalValueMap = {
  'sharp': AccidentalValue.sharp,
  'natural': AccidentalValue.natural,
  'flat': AccidentalValue.flat,
  'double-sharp': AccidentalValue.doubleSharp,
  'sharp-sharp': AccidentalValue.sharpSharp,
  'flat-flat': AccidentalValue.flatFlat,
  'natural-sharp': AccidentalValue.naturalSharp,
  'natural-flat': AccidentalValue.naturalFlat,
  'quarter-flat': AccidentalValue.quarterFlat,
  'quarter-sharp': AccidentalValue.quarterSharp,
  'three-quarters-flat': AccidentalValue.threeQuartersFlat,
  'three-quarters-sharp': AccidentalValue.threeQuartersSharp,
  'sharp-down': AccidentalValue.sharpDown,
  'sharp-up': AccidentalValue.sharpUp,
  'natural-down': AccidentalValue.naturalDown,
  'natural-up': AccidentalValue.naturalUp,
  'flat-down': AccidentalValue.flatDown,
  'flat-up': AccidentalValue.flatUp,
  'double-sharp-down': AccidentalValue.doubleSharpDown,
  'double-sharp-up': AccidentalValue.doubleSharpUp,
  'flat-flat-down': AccidentalValue.flatFlatDown,
  'flat-flat-up': AccidentalValue.flatFlatUp,
  'arrow-down': AccidentalValue.arrowDown,
  'arrow-up': AccidentalValue.arrowUp,
  'triple-sharp': AccidentalValue.tripleSharp,
  'triple-flat': AccidentalValue.tripleFlat,
  'slash-quarter-sharp': AccidentalValue.slashQuarterSharp,
  'slash-sharp': AccidentalValue.slashSharp,
  'slash-flat': AccidentalValue.slashFlat,
  'double-slash-flat': AccidentalValue.doubleSlashFlat,
  'sharp-1': AccidentalValue.sharp1,
  'sharp-2': AccidentalValue.sharp2,
  'sharp-3': AccidentalValue.sharp3,
  'sharp-5': AccidentalValue.sharp5,
  'flat-1': AccidentalValue.flat1,
  'flat-2': AccidentalValue.flat2,
  'flat-3': AccidentalValue.flat3,
  'flat-4': AccidentalValue.flat4,
  'sori': AccidentalValue.sori,
  'koron': AccidentalValue.koron,
  'other': AccidentalValue.other,
};

const accidentalValueToString = {
  AccidentalValue.sharp: 'sharp',
  AccidentalValue.natural: 'natural',
  AccidentalValue.flat: 'flat',
  AccidentalValue.doubleSharp: 'double-sharp',
  AccidentalValue.sharpSharp: 'sharp-sharp',
  AccidentalValue.flatFlat: 'flat-flat',
  AccidentalValue.naturalSharp: 'natural-sharp',
  AccidentalValue.naturalFlat: 'natural-flat',
  AccidentalValue.quarterFlat: 'quarter-flat',
  AccidentalValue.quarterSharp: 'quarter-sharp',
  AccidentalValue.threeQuartersFlat: 'three-quarters-flat',
  AccidentalValue.threeQuartersSharp: 'three-quarters-sharp',
  AccidentalValue.sharpDown: 'sharp-down',
  AccidentalValue.sharpUp: 'sharp-up',
  AccidentalValue.naturalDown: 'natural-down',
  AccidentalValue.naturalUp: 'natural-up',
  AccidentalValue.flatDown: 'flat-down',
  AccidentalValue.flatUp: 'flat-up',
  AccidentalValue.doubleSharpDown: 'double-sharp-down',
  AccidentalValue.doubleSharpUp: 'double-sharp-up',
  AccidentalValue.flatFlatDown: 'flat-flat-down',
  AccidentalValue.flatFlatUp: 'flat-flat-up',
  AccidentalValue.arrowDown: 'arrow-down',
  AccidentalValue.arrowUp: 'arrow-up',
  AccidentalValue.tripleSharp: 'triple-sharp',
  AccidentalValue.tripleFlat: 'triple-flat',
  AccidentalValue.slashQuarterSharp: 'slash-quarter-sharp',
  AccidentalValue.slashSharp: 'slash-sharp',
  AccidentalValue.slashFlat: 'slash-flat',
  AccidentalValue.doubleSlashFlat: 'double-slash-flat',
  AccidentalValue.sharp1: 'sharp-1',
  AccidentalValue.sharp2: 'sharp-2',
  AccidentalValue.sharp3: 'sharp-3',
  AccidentalValue.sharp5: 'sharp-5',
  AccidentalValue.flat1: 'flat-1',
  AccidentalValue.flat2: 'flat-2',
  AccidentalValue.flat3: 'flat-3',
  AccidentalValue.flat4: 'flat-4',
  AccidentalValue.sori: 'sori',
  AccidentalValue.koron: 'koron',
  AccidentalValue.other: 'other',
};

AccidentalValue parseAccidentalValue(String str) =>
    accidentalValueMap[str] ?? AccidentalValue.other;
